#!/bin/bash
set -eu

cmd=$1
dir=$2
shift 2

case "$cmd" in
setup)
	rm -rf $dir/root
	mkdir -p $dir/root
	exit 0
	;;

copy)
	for file in "$@"; do
		cp -a $file $dir/root
	done
	exit 0
	;;

libs)
	cd $dir/root
	for lib in $(ldd "$@" | grep -o '/[^ ]*' | sort -u); do
		if [[ -f $lib ]]; then
			echo "installing lib $lib"
			mkdir -p ./$(dirname $lib)
			cp $lib ./$lib
		fi
	done
	exit 0
	;;

clean)
	find $dir -type f -name '.keep' -exec rm \{} \;
	exit 0
	;;

*)
	echo "unrecognized command '$cmd'"
	exit 0
	;;

esac
