#!/bin/bash

tags='host=web1,env=staging'
start=$(date -d '2001-01-01 01:01:01' +%s)000
while read x; do
  echo "cpu $tags $start $x"
  case "$tags" in
  host=web1,env=staging) tags='host=web1,env=prod'    ;;
  host=web1,env=prod)    tags='host=web2,env=prod'    ;;
  host=web2,env=prod)    tags='host=web1,env=staging'
                         start=$(expr $start + 60000) ;;
  esac
done
