#!/bin/bash

if [[ -z "$1" ]]; then
  echo >&2 "USAGE: $0 N"
  exit 1;
fi

./t/randata $1 | while read x; do
  echo "cpu host=localhost,env=staging $(date +%s)000 $x"
  echo "cpu host=localhost,env=develop $(date +%s)000 $x"
  sleep 0.1
done
